spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: student
    password: student
  application:
    name: studentservice
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  client:
    enabled: true
    register-with-eureka: true
    service-url:
        defaultZone: http://localhost:8761/eureka/
